version: '3'

#reference https://github.com/bitnami/bitnami-docker-sonarqube
services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:10-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - sonarnet
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  sonarqube:
    image: docker.io/bitnami/sonarqube:7.9.4
    expose:
      - 9000
      - 5555
      - 5000
    ports:
      - '9000:9000'
      - '5555:5555'
    networks:
      - sonarnet
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1234
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_PASSWORD=bitnami1234
    volumes:
      - sonarqube_data:/bitnami
  gitlab:
    image: gitlab/gitlab-ce
    networks:
      - sonarnet
    expose:
      - 80
      - 443
    ports:
      - "443:443"
      - "80:80"
networks:
  sonarnet:
volumes:
  sonarqube_data:
    driver: local
  postgresql_data:
    driver: local
